image: node:alpine

cache:
  paths:
    - node_modules/

before_script:


stages:
  - test
  - deploy


test:
  stage: test
  script:
    - yarn install
    - CI=true yarn test

production:
  stage: deploy
  script:
  - apk update
  - apk upgrade
  - apk add bash curl-dev ruby-dev  ruby ruby-bundler build-base libffi-dev ruby-irb ruby-rdoc git curl
  - gem install dpl
  - dpl --provider=heroku --app=simplybook-frontend --api-key=$HEROKU_PRODUCTION_API_KEY # saved in CI/CD Pipelines -> secret variables
  when: manual
#  only:
#  - master
