image: node:alpine

cache:
  paths:
    - node_modules/

before_script:


stages:
  - test
  - deploy


test:
  stage: test
  script:
    - yarn install
    - CI=true yarn test

production:
  stage: deploy
  script:
  - apk update
  - apk add rubygems ruby-dev 
  - gem install dpl
  - dpl --provider=heroku --app=simplybook-dashboard --api-key=$HEROKU_PRODUCTION_API_KEY # saved in CI/CD Pipelines -> secret variables
  when: manual
#  only:
#  - master
